### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by sunwarm2001** [MediaBrain-SJTU/DISAM#1]
Great work indeed. I'm a beginner in this field, and I've encountered an issue. I noticed that the downloaded dataset is inconsistent with the data/*_dataset.py file, such as missing "{self.domain_name}_{split_dict[self.split]}_kfold' + '.txt'" for PACS dataset. If possible, could you please provide a download link for the dataset?

**Comment by FrankZhangRp** [comment]
Here are the links of PACS download: https://paperswithcode.com/dataset/pacs, https://dali-dl.github.io/project_iccv2017.html. And you can find the download link of all of five datasets at https://github.com/facebookresearch/DomainBed.
